/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "commit.h"

bool_t
xdr_TxnID (XDR *xdrs, TxnID *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->txn_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PrepareResult (XDR *xdrs, PrepareResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ok))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->info, 256))
		 return FALSE;
	return TRUE;
}
