/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMIT_H_RPCGEN
#define _COMMIT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct TxnID {
	int txn_id;
};
typedef struct TxnID TxnID;

struct PrepareResult {
	int ok;
	char *info;
};
typedef struct PrepareResult PrepareResult;

#define COMMIT_PROG 0x20000001
#define COMMIT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PREPARE 1
extern  PrepareResult * prepare_1(TxnID , CLIENT *);
extern  PrepareResult * prepare_1_svc(TxnID , struct svc_req *);
#define COMMIT 2
extern  int * commit_1(TxnID , CLIENT *);
extern  int * commit_1_svc(TxnID , struct svc_req *);
#define ABORT 3
extern  int * abort_1(TxnID , CLIENT *);
extern  int * abort_1_svc(TxnID , struct svc_req *);
#define STATUS 4
extern  int * status_1(TxnID , CLIENT *);
extern  int * status_1_svc(TxnID , struct svc_req *);
extern int commit_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PREPARE 1
extern  PrepareResult * prepare_1();
extern  PrepareResult * prepare_1_svc();
#define COMMIT 2
extern  int * commit_1();
extern  int * commit_1_svc();
#define ABORT 3
extern  int * abort_1();
extern  int * abort_1_svc();
#define STATUS 4
extern  int * status_1();
extern  int * status_1_svc();
extern int commit_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_TxnID (XDR *, TxnID*);
extern  bool_t xdr_PrepareResult (XDR *, PrepareResult*);

#else /* K&R C */
extern bool_t xdr_TxnID ();
extern bool_t xdr_PrepareResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMMIT_H_RPCGEN */
